ParkJong-Hun/Animal_Island

app/src/main/java/petstone/project/animalisland/activity/RegisterActivity.java
회원가입 입력 체크 구현.(성별 빼고)
데이터베이스(이메일, 비밀번호 외 회원정보) 부분은 아직 안구현.
=> 2021/09/27 16:57 일반 회원가입 성별 빼고 다 함.

app/src/main/java/petstone/project/animalisland/activity/RegisterActivity.java
중복확인 아직 안했고
성별은 지금 EditText로 되어 있는데, 이거 버튼이나 체크박스로 나중에 2개 중 고를 수 있게 수정해야 돼서 Male 기본값으로 함.
그리고 아이디, 닉네임, 비밀번호, 이메일 글자 길이 제한 아직 못 정함.
아직 업데이트 하면 안됨.
=> 2021/09/28 17:26 회원가입 80% 정도 완성

app/src/main/java/petstone/project/animalisland/activity/RegisterActivity.java
=> 2021/09/28 17:59 회원가입 90% 정도 완성

app/src/main/java/petstone/project/animalisland/activity/RegisterActivity.java
=> 2021/09/30 09:58 기본 회원가입 완성

app/src/main/res/layout/login.xml, app/src/main/res/layout/user_create.xml
=> 2021/09/30 10:04 비밀번호 별표화

app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java
=> 11/08 리사이클러뷰 연동

app/src/main/java/petstone/project/animalisland/activity/ChatActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/other/ChatMessage.java
=> 2021/11/09 14:21 펫프렌즈에서 채팅 생성, 채팅 입력 데이터 전송 됨.

app/src/main/java/petstone/project/animalisland/activity/ChatActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/other/ChatMessage.java, app/src/main/java/petstone/project/animalisland/other/ChatMessageAdapter.java, app/src/main/res/layout/chat.xml, app/src/main/res/layout/chat_message.xml
=> 2021/11/09 18:44 채팅 메시지 동기화!

app/build.gradle, app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUserList_CustomAdapter.java
=> 2021/11/09 10:30 검색 형태만 구현

app/src/main/AndroidManifest.xml, app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/activity/ScheduleActivity.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendFireAdapter.java, app/src/main/java/petstone/project/animalisland/other/PetfriendFireUser.java, app/src/main/res/drawable/cell_shape.xml, app/src/main/res/layout/mypage_petfriend_apply.xml, app/src/main/res/layout/petfriend_component.xml, app/src/main/res/layout/schedule_table.xml, app/src/main/res/menu/menu_option.xml
=> 11/13 펫프랜즈 요일 선택 추가

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java
=> 11/14 자격증 이미지 한개 불러옴

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java
=> 11/15 자격증 이미지 불러옴

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUserList_CustomAdapter.java, app/src/main/res/layout/petfriend_user_list_component.xml, app/src/main/res/layout/petfriend_user_select.xml
=> 11/15 자격증이미지 프로필파일 불러옴

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/activity/WebviewActivity.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java
=> 11/15 펫프렌즈 수정

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java
=> 11-15 팻프렌즈 사진 안올라가는거 고침

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java
=> 11/15 사진업로드시 기존 사진 삭제 

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUserList_CustomAdapter.java, app/src/main/res/layout/mypage_petfriend_apply.xml, app/src/main/res/layout/petfriend_component.xml, app/src/main/res/layout/petfriend_user_select.xml
=> 11/16 펫프랜즈 수정 추가 + UI 살짝

app/src/main/AndroidManifest.xml, app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java
=> 11/16 삭제/수정 내글보기 버튼 만듬

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUserList_CustomAdapter.java, app/src/main/res/layout/mypage_petfriend_apply.xml
=> 11/17 필터와 활동분야 남음

app/src/main/AndroidManifest.xml, app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/ScheduleActivity.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendFireUser.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java, app/src/main/res/drawable/cell_shape.xml, app/src/main/res/drawable/check_box.xml, app/src/main/res/layout/mypage_petfriend_apply.xml, app/src/main/res/layout/schedule_table.xml
=> 11-17 스케줄 ui 수정

app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUser.java, app/src/main/res/layout/petfriend_component.xml
=> 11/17 활동 필터 구현

app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/java/petstone/project/animalisland/other/PetfriendFireAdapter.java, app/src/main/java/petstone/project/animalisland/other/PetfriendFireUser.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUserList_CustomAdapter.java
11/18 실시간 구현 및 필터 구현 ui,예외처리 남음
=> 11/18 실시간 구현 및 필터 구현 ui,예외처리 남음

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java
=> 11/20 거의 완성

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java
=> 11/20 펫프렌즈 신청시 프로필이미지 예외처리

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java
=> 11/20 가입 예외처리

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java
=> 11/20 수정시 예외처리

app/src/main/java/petstone/project/animalisland/activity/ScheduleActivity.java, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java
=> 11/21 스케줄엑티비티 예외처리

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/RehomeFreeSubmitActivity.java, app/src/main/java/petstone/project/animalisland/activity/RehomeSellSubmitActivity.java
=> 11/22 세종시검색 오류고침

.idea/deploymentTargetDropDown.xml, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/res/layout/mypage_petfriend_apply.xml, app/src/main/res/layout/schedule_table.xml
=> 11/23 수정시 실시간 반영

.idea/deploymentTargetDropDown.xml, app/src/main/AndroidManifest.xml, app/src/main/java/petstone/project/animalisland/activity/FullImageActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java, app/src/main/java/petstone/project/animalisland/activity/SelectFreeRehomeActivity.java, app/src/main/java/petstone/project/animalisland/other/FreeSelectImageAdapter.java, app/src/main/java/petstone/project/animalisland/other/SellSelectImageAdapter.java, app/src/main/res/layout/fullimg_activity.xml
=> 11/24 마무리/분양 펫프랜즈 이미지 클릭시 확대

app/src/main/java/petstone/project/animalisland/activity/MypagePetfriendApplyActivity.java, app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java
11/24 펫프렌즈 완성, 이미지 클릭시 확대(분양 펫프렌지)
=> 11/24 펫프렌즈 완성, 이미지 클릭시 확대(분양 펫프렌지)

app/src/main/java/petstone/project/animalisland/other/PetfriendFireAdapter.java, app/src/main/java/petstone/project/animalisland/other/PetfriendUserList_CustomAdapter.java
=> 11/25 점수오류 고침

.idea/deploymentTargetDropDown.xml, app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java, app/src/main/res/layout/petfriend_user_list_component.xml
=> 11/25 마지막 오류 수정
